### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by shitoushan** [mlampros/textTinyR#4]
```devtools::install_github(repo = 'mlampros/textTinyR')```

gives me

```
Downloading GitHub repo mlampros/textTinyR@master
from URL https://api.github.com/repos/mlampros/textTinyR/zipball/master
Installing textTinyR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  '/private/var/folders/ly/jwh1_hf12_97wmdzy1skxl0h0000gn/T/RtmpGPE1US/devtools5db7277a117/mlampros-textTinyR-5763ce1'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘textTinyR’ ...
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../inst/include/  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/BH/include" -I/usr/local/include  -fopenmp -DARMA_64BIT_WORD -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘textTinyR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/textTinyR’
Installation failed: Command failed (1)
```

I'm on 

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2

I should probably mention that I followed the instructions mentioned here

https://www.rdocumentation.org/packages/textTinyR/versions/1.0.9

but ``` devtools::install_github(repo = 'mlampros/textTinyR', clean = TRUE)```
still gives me error:

```
* installing *source* package ‘textTinyR’ ...
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../inst/include/  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/BH/include" -I/usr/local/include  -fopenmp -DARMA_64BIT_WORD -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘textTinyR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/textTinyR’
```

**Comment by mlampros** [comment]
@shitoushan,

* I currently submitted textTinyR version 1.1.1 to CRAN, which does not require that the user has to take all the steps mentioned in the README file of version 1.0.9 ( I removed boost-locale and boost_system from the Makevars file). So [once you see version 1.1.1](https://cran.r-project.org/web/checks/check_results_textTinyR.html) you will be able to simply do,

```R

install.packages(repo = 'mlampros/textTinyR')

``` 

* As mentioned in this [blog-post](https://asieira.github.io/using-openmp-with-r-packages-in-os-x.html) 

```R

"Turns out the binary version of packages available at CRAN are not compiled to use OpenMP, 
since not all systems are equipped to support it. Moreover, if you try to install the package from
source on OS X, it will try to use clang / clang++ which in my experience does not support
OpenMP either."

``` 

Therefore if you want to install from source on Macintosh then you should have OpenMP ( -fopenmp ) enabled in order to use the textTinyR package, that's why you receive the error 

```R

clang: error: unsupported option '-fopenmp'

```

Besides the [blog-post](https://asieira.github.io/using-openmp-with-r-packages-in-os-x.html)  that I mentioned [another one](http://www.thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/) explains in detail how to enable OpenMP on Macintosh (in case you want to take advantage of parallization)

**Comment by shitoushan** [comment]
Thank you! I didn't manage to uninstall gfortran 6.3, but for some reason installing clang was enough.
