### ISSUE TITLE
Cannot Install on Windows or Mac

### ISSUE THREAD

**Issue by tsouchlarakis** [mlampros/textTinyR#5]
I have tried for several hours to install using all resources mentioned in the previous issues and by searching the web tirelessly but I am unable to install this package either on Mac or Windows, both running R version 3.4.3.

For the most part I get a compilation error. I've installed Command Line Tools on my Mac and RTOOLS on my Windows machine, and no luck. I tried installing from source, github, straight from CRAN, all several different ways and I can't get the package to compile. You have really cool stuff in this package and I would love to be able to use it! Please let me know if you have any suggestions. I've tried following all instructions but have not been successful. Thank you very much.

**Comment by mlampros** [comment]
@tsouchlarakis I'm sorry for the late reply,

the *textTinyR* package [test results](https://cran.r-project.org/web/checks/check_results_textTinyR.html) for version 1.1.1 show that the package can be installed error free on Linux, Windows. On Macintosh as of version 1.1.1 it can be installed on *r-release-osx-x86_64* but it has to be tested for *r-oldrel-osx-x86_64* (currently is version 1.1.0).

Would you mind sharing the error that you receive?

**Comment by tsouchlarakis** [comment]
@mlampros Thanks for the reply and help. I was actually able to install `textTinyR` simply with `install.packages("textTinyR")` after restarting my R session. Because of that I don't have the original error message, but when I went to install another one of your packages, `fastTextR` (also great by the way) on Windows I got a similar message when running `devtools::install_github('mlampros/fastTextR')`

```
*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.3/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="fastTextR.dll" OBJECTS="RcppExports.o args.o dictionary.o fasttext.o main.o matrix.o model.o utils.o vector.o"' had status 127
ERROR: compilation failed for package 'fastTextR'
* removing 'C:/Users/User/Documents/R/win-library/3.4/fastTextR'
In R CMD INSTALL
Installation failed: Command failed (1)
```

The common denominator is the `compliation failed` part of the error message.

**Comment by tsouchlarakis** [comment]
My question, in order to get `textTinyR` to run on Mac, what would I need to do? I'm unfamiliar with the *r-release-osx-x86_64* and *r-oldrel-osx-x86_64* that you mentioned. Thanks!

**Comment by mlampros** [comment]
@tsouchlarakis I struggle also a lot when I have to test the packages on all three operating systems (Linux, Macintosh, Windows). 

The message that you get when you try to install the fasttextR package is probably because you don't have Rtools installed. I found a similar issue on the web "https://github.com/tidyverse/dplyr/issues/165".

If you are not familiar with Rtools or how to make R work on macintosh, I'd suggest (besides other resources on the web) to take a look in [this blog](https://thecoatlessprofessor.com/) and especially for windows [here](https://thecoatlessprofessor.com/programming/installing-rtools-for-compiled-code-via-rcpp/) and for macintosh [here](https://thecoatlessprofessor.com/programming/r-compiler-tools-for-rcpp-on-macos/).

If you receive an error on Macintosh then it's highly probable that it has to do with the boost library that was a system requirement in the previous version of the textTinyR package. That is just an assumption, because I don't know what kind of error you receive. However, if you have *brew* installed then you can install the *boost* library (if not already installed) using 

```R

brew install boost

brew update

```
please let me know if it worked.

**Comment by mlampros** [comment]
I hope you were able to install the package successfully. 

I close the issue for now, feel free to reopen it.
